version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.7.2" > ~/.ruby-version
      - run:
          name: Which bundler?
          command: gem install bundler -v 2.2.26
      - run:
          name: Bundle
          command: bundle install
      - run:
          name: Test suite
          command: bundle exec rspec